/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WebWorkspaceIndexRouteImport } from './routes/web-workspace/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SrmPortalsIndexRouteImport } from './routes/srm-portals/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProcessesIndexRouteImport } from './routes/processes/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SrmPortalsPortalIdRouteImport } from './routes/srm-portals/$portalId'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ProcessesInstanceIdRouteImport } from './routes/processes/$instanceId'
import { Route as ProcessInstancesStatementsRouteImport } from './routes/process-instances/statements'
import { Route as ProcessesInstanceIdIndexRouteImport } from './routes/processes/$instanceId/index'
import { Route as ProcessesInstanceIdDatesRouteImport } from './routes/processes/$instanceId/dates'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebWorkspaceIndexRoute = WebWorkspaceIndexRouteImport.update({
  id: '/web-workspace/',
  path: '/web-workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SrmPortalsIndexRoute = SrmPortalsIndexRouteImport.update({
  id: '/srm-portals/',
  path: '/srm-portals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesIndexRoute = ProcessesIndexRouteImport.update({
  id: '/processes/',
  path: '/processes/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SrmPortalsPortalIdRoute = SrmPortalsPortalIdRouteImport.update({
  id: '/srm-portals/$portalId',
  path: '/srm-portals/$portalId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesInstanceIdRoute = ProcessesInstanceIdRouteImport.update({
  id: '/processes/$instanceId',
  path: '/processes/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessInstancesStatementsRoute =
  ProcessInstancesStatementsRouteImport.update({
    id: '/process-instances/statements',
    path: '/process-instances/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessesInstanceIdIndexRoute =
  ProcessesInstanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProcessesInstanceIdRoute,
  } as any)
const ProcessesInstanceIdDatesRoute =
  ProcessesInstanceIdDatesRouteImport.update({
    id: '/dates',
    path: '/dates',
    getParentRoute: () => ProcessesInstanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/process-instances/statements': typeof ProcessInstancesStatementsRoute
  '/processes/$instanceId': typeof ProcessesInstanceIdRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/srm-portals/$portalId': typeof SrmPortalsPortalIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/processes/': typeof ProcessesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/srm-portals/': typeof SrmPortalsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/web-workspace/': typeof WebWorkspaceIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/processes/$instanceId/dates': typeof ProcessesInstanceIdDatesRoute
  '/processes/$instanceId/': typeof ProcessesInstanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/process-instances/statements': typeof ProcessInstancesStatementsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/srm-portals/$portalId': typeof SrmPortalsPortalIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/processes': typeof ProcessesIndexRoute
  '/runs': typeof RunsIndexRoute
  '/srm-portals': typeof SrmPortalsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/web-workspace': typeof WebWorkspaceIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/processes/$instanceId/dates': typeof ProcessesInstanceIdDatesRoute
  '/processes/$instanceId': typeof ProcessesInstanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/process-instances/statements': typeof ProcessInstancesStatementsRoute
  '/processes/$instanceId': typeof ProcessesInstanceIdRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/srm-portals/$portalId': typeof SrmPortalsPortalIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/processes/': typeof ProcessesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/srm-portals/': typeof SrmPortalsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/web-workspace/': typeof WebWorkspaceIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/processes/$instanceId/dates': typeof ProcessesInstanceIdDatesRoute
  '/processes/$instanceId/': typeof ProcessesInstanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/components'
    | '/dashboard'
    | '/settings'
    | '/process-instances/statements'
    | '/processes/$instanceId'
    | '/runs/$runId'
    | '/srm-portals/$portalId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/workflows/$workflowId'
    | '/processes/'
    | '/runs/'
    | '/srm-portals/'
    | '/tasks/'
    | '/web-workspace/'
    | '/workflows/'
    | '/processes/$instanceId/dates'
    | '/processes/$instanceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/components'
    | '/dashboard'
    | '/settings'
    | '/process-instances/statements'
    | '/runs/$runId'
    | '/srm-portals/$portalId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/workflows/$workflowId'
    | '/processes'
    | '/runs'
    | '/srm-portals'
    | '/tasks'
    | '/web-workspace'
    | '/workflows'
    | '/processes/$instanceId/dates'
    | '/processes/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/components'
    | '/dashboard'
    | '/settings'
    | '/process-instances/statements'
    | '/processes/$instanceId'
    | '/runs/$runId'
    | '/srm-portals/$portalId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/workflows/$workflowId'
    | '/processes/'
    | '/runs/'
    | '/srm-portals/'
    | '/tasks/'
    | '/web-workspace/'
    | '/workflows/'
    | '/processes/$instanceId/dates'
    | '/processes/$instanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  ComponentsRoute: typeof ComponentsRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  ProcessInstancesStatementsRoute: typeof ProcessInstancesStatementsRoute
  ProcessesInstanceIdRoute: typeof ProcessesInstanceIdRouteWithChildren
  RunsRunIdRoute: typeof RunsRunIdRoute
  SrmPortalsPortalIdRoute: typeof SrmPortalsPortalIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  ProcessesIndexRoute: typeof ProcessesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SrmPortalsIndexRoute: typeof SrmPortalsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WebWorkspaceIndexRoute: typeof WebWorkspaceIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-workspace/': {
      id: '/web-workspace/'
      path: '/web-workspace'
      fullPath: '/web-workspace/'
      preLoaderRoute: typeof WebWorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srm-portals/': {
      id: '/srm-portals/'
      path: '/srm-portals'
      fullPath: '/srm-portals/'
      preLoaderRoute: typeof SrmPortalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/': {
      id: '/processes/'
      path: '/processes'
      fullPath: '/processes/'
      preLoaderRoute: typeof ProcessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srm-portals/$portalId': {
      id: '/srm-portals/$portalId'
      path: '/srm-portals/$portalId'
      fullPath: '/srm-portals/$portalId'
      preLoaderRoute: typeof SrmPortalsPortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/$instanceId': {
      id: '/processes/$instanceId'
      path: '/processes/$instanceId'
      fullPath: '/processes/$instanceId'
      preLoaderRoute: typeof ProcessesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-instances/statements': {
      id: '/process-instances/statements'
      path: '/process-instances/statements'
      fullPath: '/process-instances/statements'
      preLoaderRoute: typeof ProcessInstancesStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/$instanceId/': {
      id: '/processes/$instanceId/'
      path: '/'
      fullPath: '/processes/$instanceId/'
      preLoaderRoute: typeof ProcessesInstanceIdIndexRouteImport
      parentRoute: typeof ProcessesInstanceIdRoute
    }
    '/processes/$instanceId/dates': {
      id: '/processes/$instanceId/dates'
      path: '/dates'
      fullPath: '/processes/$instanceId/dates'
      preLoaderRoute: typeof ProcessesInstanceIdDatesRouteImport
      parentRoute: typeof ProcessesInstanceIdRoute
    }
  }
}

interface ProcessesInstanceIdRouteChildren {
  ProcessesInstanceIdDatesRoute: typeof ProcessesInstanceIdDatesRoute
  ProcessesInstanceIdIndexRoute: typeof ProcessesInstanceIdIndexRoute
}

const ProcessesInstanceIdRouteChildren: ProcessesInstanceIdRouteChildren = {
  ProcessesInstanceIdDatesRoute: ProcessesInstanceIdDatesRoute,
  ProcessesInstanceIdIndexRoute: ProcessesInstanceIdIndexRoute,
}

const ProcessesInstanceIdRouteWithChildren =
  ProcessesInstanceIdRoute._addFileChildren(ProcessesInstanceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  ComponentsRoute: ComponentsRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  ProcessInstancesStatementsRoute: ProcessInstancesStatementsRoute,
  ProcessesInstanceIdRoute: ProcessesInstanceIdRouteWithChildren,
  RunsRunIdRoute: RunsRunIdRoute,
  SrmPortalsPortalIdRoute: SrmPortalsPortalIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  ProcessesIndexRoute: ProcessesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SrmPortalsIndexRoute: SrmPortalsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  WebWorkspaceIndexRoute: WebWorkspaceIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
