/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WebWorkspaceIndexRouteImport } from './routes/web-workspace/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SrmPortalsIndexRouteImport } from './routes/srm-portals/index'
import { Route as SchedulersIndexRouteImport } from './routes/schedulers/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProcessesIndexRouteImport } from './routes/processes/index'
import { Route as PortalCategoriesIndexRouteImport } from './routes/portal-categories/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SrmPortalsPortalIdRouteImport } from './routes/srm-portals/$portalId'
import { Route as SchedulersJobIdRouteImport } from './routes/schedulers/$jobId'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ProcessesInstanceIdRouteImport } from './routes/processes/$instanceId'
import { Route as ProcessInstancesStatementsRouteImport } from './routes/process-instances/statements'
import { Route as ProcessInstancesInvoicePackingRouteImport } from './routes/process-instances/invoice-packing'
import { Route as PortalCategoriesCategoryRouteImport } from './routes/portal-categories/$category'
import { Route as ProcessesInstanceIdIndexRouteImport } from './routes/processes/$instanceId/index'
import { Route as ProcessInstancesStatementsIndexRouteImport } from './routes/process-instances/statements/index'
import { Route as ProcessInstancesInvoicePackingIndexRouteImport } from './routes/process-instances/invoice-packing/index'
import { Route as ProcessesInstanceIdDatesRouteImport } from './routes/processes/$instanceId/dates'
import { Route as ProcessInstancesStatementsGenerateRouteImport } from './routes/process-instances/statements/generate'
import { Route as ProcessInstancesStatementsBillIdRouteImport } from './routes/process-instances/statements/$billId'
import { Route as ProcessInstancesInvoicePackingInstanceIdRouteImport } from './routes/process-instances/invoice-packing/$instanceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebWorkspaceIndexRoute = WebWorkspaceIndexRouteImport.update({
  id: '/web-workspace/',
  path: '/web-workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SrmPortalsIndexRoute = SrmPortalsIndexRouteImport.update({
  id: '/srm-portals/',
  path: '/srm-portals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulersIndexRoute = SchedulersIndexRouteImport.update({
  id: '/schedulers/',
  path: '/schedulers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesIndexRoute = ProcessesIndexRouteImport.update({
  id: '/processes/',
  path: '/processes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCategoriesIndexRoute = PortalCategoriesIndexRouteImport.update({
  id: '/portal-categories/',
  path: '/portal-categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SrmPortalsPortalIdRoute = SrmPortalsPortalIdRouteImport.update({
  id: '/srm-portals/$portalId',
  path: '/srm-portals/$portalId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulersJobIdRoute = SchedulersJobIdRouteImport.update({
  id: '/schedulers/$jobId',
  path: '/schedulers/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesInstanceIdRoute = ProcessesInstanceIdRouteImport.update({
  id: '/processes/$instanceId',
  path: '/processes/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessInstancesStatementsRoute =
  ProcessInstancesStatementsRouteImport.update({
    id: '/process-instances/statements',
    path: '/process-instances/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessInstancesInvoicePackingRoute =
  ProcessInstancesInvoicePackingRouteImport.update({
    id: '/process-instances/invoice-packing',
    path: '/process-instances/invoice-packing',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalCategoriesCategoryRoute =
  PortalCategoriesCategoryRouteImport.update({
    id: '/portal-categories/$category',
    path: '/portal-categories/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessesInstanceIdIndexRoute =
  ProcessesInstanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProcessesInstanceIdRoute,
  } as any)
const ProcessInstancesStatementsIndexRoute =
  ProcessInstancesStatementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProcessInstancesStatementsRoute,
  } as any)
const ProcessInstancesInvoicePackingIndexRoute =
  ProcessInstancesInvoicePackingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProcessInstancesInvoicePackingRoute,
  } as any)
const ProcessesInstanceIdDatesRoute =
  ProcessesInstanceIdDatesRouteImport.update({
    id: '/dates',
    path: '/dates',
    getParentRoute: () => ProcessesInstanceIdRoute,
  } as any)
const ProcessInstancesStatementsGenerateRoute =
  ProcessInstancesStatementsGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ProcessInstancesStatementsRoute,
  } as any)
const ProcessInstancesStatementsBillIdRoute =
  ProcessInstancesStatementsBillIdRouteImport.update({
    id: '/$billId',
    path: '/$billId',
    getParentRoute: () => ProcessInstancesStatementsRoute,
  } as any)
const ProcessInstancesInvoicePackingInstanceIdRoute =
  ProcessInstancesInvoicePackingInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => ProcessInstancesInvoicePackingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/portal-categories/$category': typeof PortalCategoriesCategoryRoute
  '/process-instances/invoice-packing': typeof ProcessInstancesInvoicePackingRouteWithChildren
  '/process-instances/statements': typeof ProcessInstancesStatementsRouteWithChildren
  '/processes/$instanceId': typeof ProcessesInstanceIdRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/schedulers/$jobId': typeof SchedulersJobIdRoute
  '/srm-portals/$portalId': typeof SrmPortalsPortalIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/portal-categories/': typeof PortalCategoriesIndexRoute
  '/processes/': typeof ProcessesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/schedulers/': typeof SchedulersIndexRoute
  '/srm-portals/': typeof SrmPortalsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/web-workspace/': typeof WebWorkspaceIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/process-instances/invoice-packing/$instanceId': typeof ProcessInstancesInvoicePackingInstanceIdRoute
  '/process-instances/statements/$billId': typeof ProcessInstancesStatementsBillIdRoute
  '/process-instances/statements/generate': typeof ProcessInstancesStatementsGenerateRoute
  '/processes/$instanceId/dates': typeof ProcessesInstanceIdDatesRoute
  '/process-instances/invoice-packing/': typeof ProcessInstancesInvoicePackingIndexRoute
  '/process-instances/statements/': typeof ProcessInstancesStatementsIndexRoute
  '/processes/$instanceId/': typeof ProcessesInstanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/portal-categories/$category': typeof PortalCategoriesCategoryRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/schedulers/$jobId': typeof SchedulersJobIdRoute
  '/srm-portals/$portalId': typeof SrmPortalsPortalIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/portal-categories': typeof PortalCategoriesIndexRoute
  '/processes': typeof ProcessesIndexRoute
  '/runs': typeof RunsIndexRoute
  '/schedulers': typeof SchedulersIndexRoute
  '/srm-portals': typeof SrmPortalsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/web-workspace': typeof WebWorkspaceIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/process-instances/invoice-packing/$instanceId': typeof ProcessInstancesInvoicePackingInstanceIdRoute
  '/process-instances/statements/$billId': typeof ProcessInstancesStatementsBillIdRoute
  '/process-instances/statements/generate': typeof ProcessInstancesStatementsGenerateRoute
  '/processes/$instanceId/dates': typeof ProcessesInstanceIdDatesRoute
  '/process-instances/invoice-packing': typeof ProcessInstancesInvoicePackingIndexRoute
  '/process-instances/statements': typeof ProcessInstancesStatementsIndexRoute
  '/processes/$instanceId': typeof ProcessesInstanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/portal-categories/$category': typeof PortalCategoriesCategoryRoute
  '/process-instances/invoice-packing': typeof ProcessInstancesInvoicePackingRouteWithChildren
  '/process-instances/statements': typeof ProcessInstancesStatementsRouteWithChildren
  '/processes/$instanceId': typeof ProcessesInstanceIdRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRoute
  '/schedulers/$jobId': typeof SchedulersJobIdRoute
  '/srm-portals/$portalId': typeof SrmPortalsPortalIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/portal-categories/': typeof PortalCategoriesIndexRoute
  '/processes/': typeof ProcessesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/schedulers/': typeof SchedulersIndexRoute
  '/srm-portals/': typeof SrmPortalsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/web-workspace/': typeof WebWorkspaceIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/process-instances/invoice-packing/$instanceId': typeof ProcessInstancesInvoicePackingInstanceIdRoute
  '/process-instances/statements/$billId': typeof ProcessInstancesStatementsBillIdRoute
  '/process-instances/statements/generate': typeof ProcessInstancesStatementsGenerateRoute
  '/processes/$instanceId/dates': typeof ProcessesInstanceIdDatesRoute
  '/process-instances/invoice-packing/': typeof ProcessInstancesInvoicePackingIndexRoute
  '/process-instances/statements/': typeof ProcessInstancesStatementsIndexRoute
  '/processes/$instanceId/': typeof ProcessesInstanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/components'
    | '/dashboard'
    | '/settings'
    | '/portal-categories/$category'
    | '/process-instances/invoice-packing'
    | '/process-instances/statements'
    | '/processes/$instanceId'
    | '/runs/$runId'
    | '/schedulers/$jobId'
    | '/srm-portals/$portalId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/workflows/$workflowId'
    | '/portal-categories/'
    | '/processes/'
    | '/runs/'
    | '/schedulers/'
    | '/srm-portals/'
    | '/tasks/'
    | '/web-workspace/'
    | '/workflows/'
    | '/process-instances/invoice-packing/$instanceId'
    | '/process-instances/statements/$billId'
    | '/process-instances/statements/generate'
    | '/processes/$instanceId/dates'
    | '/process-instances/invoice-packing/'
    | '/process-instances/statements/'
    | '/processes/$instanceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/components'
    | '/dashboard'
    | '/settings'
    | '/portal-categories/$category'
    | '/runs/$runId'
    | '/schedulers/$jobId'
    | '/srm-portals/$portalId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/workflows/$workflowId'
    | '/portal-categories'
    | '/processes'
    | '/runs'
    | '/schedulers'
    | '/srm-portals'
    | '/tasks'
    | '/web-workspace'
    | '/workflows'
    | '/process-instances/invoice-packing/$instanceId'
    | '/process-instances/statements/$billId'
    | '/process-instances/statements/generate'
    | '/processes/$instanceId/dates'
    | '/process-instances/invoice-packing'
    | '/process-instances/statements'
    | '/processes/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/components'
    | '/dashboard'
    | '/settings'
    | '/portal-categories/$category'
    | '/process-instances/invoice-packing'
    | '/process-instances/statements'
    | '/processes/$instanceId'
    | '/runs/$runId'
    | '/schedulers/$jobId'
    | '/srm-portals/$portalId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/workflows/$workflowId'
    | '/portal-categories/'
    | '/processes/'
    | '/runs/'
    | '/schedulers/'
    | '/srm-portals/'
    | '/tasks/'
    | '/web-workspace/'
    | '/workflows/'
    | '/process-instances/invoice-packing/$instanceId'
    | '/process-instances/statements/$billId'
    | '/process-instances/statements/generate'
    | '/processes/$instanceId/dates'
    | '/process-instances/invoice-packing/'
    | '/process-instances/statements/'
    | '/processes/$instanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  ComponentsRoute: typeof ComponentsRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  PortalCategoriesCategoryRoute: typeof PortalCategoriesCategoryRoute
  ProcessInstancesInvoicePackingRoute: typeof ProcessInstancesInvoicePackingRouteWithChildren
  ProcessInstancesStatementsRoute: typeof ProcessInstancesStatementsRouteWithChildren
  ProcessesInstanceIdRoute: typeof ProcessesInstanceIdRouteWithChildren
  RunsRunIdRoute: typeof RunsRunIdRoute
  SchedulersJobIdRoute: typeof SchedulersJobIdRoute
  SrmPortalsPortalIdRoute: typeof SrmPortalsPortalIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  PortalCategoriesIndexRoute: typeof PortalCategoriesIndexRoute
  ProcessesIndexRoute: typeof ProcessesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SchedulersIndexRoute: typeof SchedulersIndexRoute
  SrmPortalsIndexRoute: typeof SrmPortalsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WebWorkspaceIndexRoute: typeof WebWorkspaceIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-workspace/': {
      id: '/web-workspace/'
      path: '/web-workspace'
      fullPath: '/web-workspace/'
      preLoaderRoute: typeof WebWorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srm-portals/': {
      id: '/srm-portals/'
      path: '/srm-portals'
      fullPath: '/srm-portals/'
      preLoaderRoute: typeof SrmPortalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedulers/': {
      id: '/schedulers/'
      path: '/schedulers'
      fullPath: '/schedulers/'
      preLoaderRoute: typeof SchedulersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/': {
      id: '/processes/'
      path: '/processes'
      fullPath: '/processes/'
      preLoaderRoute: typeof ProcessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-categories/': {
      id: '/portal-categories/'
      path: '/portal-categories'
      fullPath: '/portal-categories/'
      preLoaderRoute: typeof PortalCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srm-portals/$portalId': {
      id: '/srm-portals/$portalId'
      path: '/srm-portals/$portalId'
      fullPath: '/srm-portals/$portalId'
      preLoaderRoute: typeof SrmPortalsPortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedulers/$jobId': {
      id: '/schedulers/$jobId'
      path: '/schedulers/$jobId'
      fullPath: '/schedulers/$jobId'
      preLoaderRoute: typeof SchedulersJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/$instanceId': {
      id: '/processes/$instanceId'
      path: '/processes/$instanceId'
      fullPath: '/processes/$instanceId'
      preLoaderRoute: typeof ProcessesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-instances/statements': {
      id: '/process-instances/statements'
      path: '/process-instances/statements'
      fullPath: '/process-instances/statements'
      preLoaderRoute: typeof ProcessInstancesStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-instances/invoice-packing': {
      id: '/process-instances/invoice-packing'
      path: '/process-instances/invoice-packing'
      fullPath: '/process-instances/invoice-packing'
      preLoaderRoute: typeof ProcessInstancesInvoicePackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-categories/$category': {
      id: '/portal-categories/$category'
      path: '/portal-categories/$category'
      fullPath: '/portal-categories/$category'
      preLoaderRoute: typeof PortalCategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/$instanceId/': {
      id: '/processes/$instanceId/'
      path: '/'
      fullPath: '/processes/$instanceId/'
      preLoaderRoute: typeof ProcessesInstanceIdIndexRouteImport
      parentRoute: typeof ProcessesInstanceIdRoute
    }
    '/process-instances/statements/': {
      id: '/process-instances/statements/'
      path: '/'
      fullPath: '/process-instances/statements/'
      preLoaderRoute: typeof ProcessInstancesStatementsIndexRouteImport
      parentRoute: typeof ProcessInstancesStatementsRoute
    }
    '/process-instances/invoice-packing/': {
      id: '/process-instances/invoice-packing/'
      path: '/'
      fullPath: '/process-instances/invoice-packing/'
      preLoaderRoute: typeof ProcessInstancesInvoicePackingIndexRouteImport
      parentRoute: typeof ProcessInstancesInvoicePackingRoute
    }
    '/processes/$instanceId/dates': {
      id: '/processes/$instanceId/dates'
      path: '/dates'
      fullPath: '/processes/$instanceId/dates'
      preLoaderRoute: typeof ProcessesInstanceIdDatesRouteImport
      parentRoute: typeof ProcessesInstanceIdRoute
    }
    '/process-instances/statements/generate': {
      id: '/process-instances/statements/generate'
      path: '/generate'
      fullPath: '/process-instances/statements/generate'
      preLoaderRoute: typeof ProcessInstancesStatementsGenerateRouteImport
      parentRoute: typeof ProcessInstancesStatementsRoute
    }
    '/process-instances/statements/$billId': {
      id: '/process-instances/statements/$billId'
      path: '/$billId'
      fullPath: '/process-instances/statements/$billId'
      preLoaderRoute: typeof ProcessInstancesStatementsBillIdRouteImport
      parentRoute: typeof ProcessInstancesStatementsRoute
    }
    '/process-instances/invoice-packing/$instanceId': {
      id: '/process-instances/invoice-packing/$instanceId'
      path: '/$instanceId'
      fullPath: '/process-instances/invoice-packing/$instanceId'
      preLoaderRoute: typeof ProcessInstancesInvoicePackingInstanceIdRouteImport
      parentRoute: typeof ProcessInstancesInvoicePackingRoute
    }
  }
}

interface ProcessInstancesInvoicePackingRouteChildren {
  ProcessInstancesInvoicePackingInstanceIdRoute: typeof ProcessInstancesInvoicePackingInstanceIdRoute
  ProcessInstancesInvoicePackingIndexRoute: typeof ProcessInstancesInvoicePackingIndexRoute
}

const ProcessInstancesInvoicePackingRouteChildren: ProcessInstancesInvoicePackingRouteChildren =
  {
    ProcessInstancesInvoicePackingInstanceIdRoute:
      ProcessInstancesInvoicePackingInstanceIdRoute,
    ProcessInstancesInvoicePackingIndexRoute:
      ProcessInstancesInvoicePackingIndexRoute,
  }

const ProcessInstancesInvoicePackingRouteWithChildren =
  ProcessInstancesInvoicePackingRoute._addFileChildren(
    ProcessInstancesInvoicePackingRouteChildren,
  )

interface ProcessInstancesStatementsRouteChildren {
  ProcessInstancesStatementsBillIdRoute: typeof ProcessInstancesStatementsBillIdRoute
  ProcessInstancesStatementsGenerateRoute: typeof ProcessInstancesStatementsGenerateRoute
  ProcessInstancesStatementsIndexRoute: typeof ProcessInstancesStatementsIndexRoute
}

const ProcessInstancesStatementsRouteChildren: ProcessInstancesStatementsRouteChildren =
  {
    ProcessInstancesStatementsBillIdRoute:
      ProcessInstancesStatementsBillIdRoute,
    ProcessInstancesStatementsGenerateRoute:
      ProcessInstancesStatementsGenerateRoute,
    ProcessInstancesStatementsIndexRoute: ProcessInstancesStatementsIndexRoute,
  }

const ProcessInstancesStatementsRouteWithChildren =
  ProcessInstancesStatementsRoute._addFileChildren(
    ProcessInstancesStatementsRouteChildren,
  )

interface ProcessesInstanceIdRouteChildren {
  ProcessesInstanceIdDatesRoute: typeof ProcessesInstanceIdDatesRoute
  ProcessesInstanceIdIndexRoute: typeof ProcessesInstanceIdIndexRoute
}

const ProcessesInstanceIdRouteChildren: ProcessesInstanceIdRouteChildren = {
  ProcessesInstanceIdDatesRoute: ProcessesInstanceIdDatesRoute,
  ProcessesInstanceIdIndexRoute: ProcessesInstanceIdIndexRoute,
}

const ProcessesInstanceIdRouteWithChildren =
  ProcessesInstanceIdRoute._addFileChildren(ProcessesInstanceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  ComponentsRoute: ComponentsRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  PortalCategoriesCategoryRoute: PortalCategoriesCategoryRoute,
  ProcessInstancesInvoicePackingRoute:
    ProcessInstancesInvoicePackingRouteWithChildren,
  ProcessInstancesStatementsRoute: ProcessInstancesStatementsRouteWithChildren,
  ProcessesInstanceIdRoute: ProcessesInstanceIdRouteWithChildren,
  RunsRunIdRoute: RunsRunIdRoute,
  SchedulersJobIdRoute: SchedulersJobIdRoute,
  SrmPortalsPortalIdRoute: SrmPortalsPortalIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  PortalCategoriesIndexRoute: PortalCategoriesIndexRoute,
  ProcessesIndexRoute: ProcessesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SchedulersIndexRoute: SchedulersIndexRoute,
  SrmPortalsIndexRoute: SrmPortalsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  WebWorkspaceIndexRoute: WebWorkspaceIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
